package com.mydia.restaurantsmartqr.model.orderList

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.parcelize.Parcelize

@Parcelize
data class OrderList(
    @SerializedName("nOrderId"                  ) var nOrderId                  : Int?            = null,
    @SerializedName("nUserId"                   ) var nUserId                   : Int?            = null,
    @SerializedName("nSupplierId"               ) var nSupplierId               : Int?            = null,
    @SerializedName("nCustomerId"               ) var nCustomerId               : Int?            = null,
    @SerializedName("cCustomerName"             ) var cCustomerName             : String?         = null,
    @SerializedName("cOrderType"                ) var cOrderType                : String?         = null,
    @SerializedName("dtGeneratedDate"           ) var dtGeneratedDate           : String?         = null,
    @SerializedName("fTotalPrice"               ) var fTotalPrice               : Double?         = null,
    @SerializedName("cPaymentTerms"             ) var cPaymentTerms             : String?         = null,
    @SerializedName("cCancellationReasons"      ) var cCancellationReasons      : String?         = null,
    @SerializedName("dtDeliveryDate"            ) var dtDeliveryDate            : String?         = null,
    @SerializedName("dtPaymentDueDate"          ) var dtPaymentDueDate          : String?         = null,
    @SerializedName("dtValidityDate"            ) var dtValidityDate            : String?         = null,
    @SerializedName("dtSpecialPriceFrom"        ) var dtSpecialPriceFrom        : String?         = null,
    @SerializedName("dtSpecialPriceTo"          ) var dtSpecialPriceTo          : String?         = null,
    @SerializedName("cOrderCode"                ) var cOrderCode                : String?         = null,
    @SerializedName("IsActive"                  ) var IsActive                  : Boolean?        = null,
    @SerializedName("IsDisable"                 ) var IsDisable                 : Boolean?        = null,
    @SerializedName("cOrderTitle"               ) var cOrderTitle               : String?         = null,
    @SerializedName("cCurrentStatus"            ) var cCurrentStatus            : String?         = null,
    @SerializedName("nEmployeeId"               ) var nEmployeeId               : Int?            = null,
    @SerializedName("cAddress"                  ) var cAddress                  : String?         = null,
    @SerializedName("cRemarks1"                 ) var cRemarks1                 : String?         = null,
    @SerializedName("cRemarks2"                 ) var cRemarks2                 : String?         = null,
    @SerializedName("cRemarks3"                 ) var cRemarks3                 : String?         = null,
    @SerializedName("Item"                      ) var Item                      : ArrayList<Items> = arrayListOf(),
    @SerializedName("GiftCard"                  ) var GiftCard                  : String?         = null,
    @SerializedName("fAmountDue"                ) var fAmountDue                : Int?            = null,
    @SerializedName("ndtlTakePaymentId"         ) var ndtlTakePaymentId         : Int?            = null,
    @SerializedName("TotalInvoice"              ) var TotalInvoice              : Int?            = null,
    @SerializedName("TotalStatus"               ) var TotalStatus               : Int?            = null,
    @SerializedName("Status"                    ) var Status                    : String?         = null,
    @SerializedName("cQuantity"                 ) var cQuantity                 : String?         = null,
    @SerializedName("cDiscountAmount"           ) var cDiscountAmount           : Int?            = null,
    @SerializedName("cDeliveryTime"             ) var cDeliveryTime             : String?         = null,
    @SerializedName("fDeliveryCharge"           ) var fDeliveryCharge           : Int?            = null,
    @SerializedName("cCurrencySymbol"           ) var cCurrencySymbol           : String?         = null,
    @SerializedName("fCouponDiscount"           ) var fCouponDiscount           : Int?            = null,
    @SerializedName("fSubTotal"                 ) var fSubTotal                 : Double?         = null,
    @SerializedName("cShippingAddress"          ) var cShippingAddress          : String?         = null,
    @SerializedName("cStoreAddress"             ) var cStoreAddress             : String?         = null,
    @SerializedName("cPaymentStatus"            ) var cPaymentStatus            : String?         = null,
    @SerializedName("cOrderCancellationReasons" ) var cOrderCancellationReasons : String?         = null,
    @SerializedName("cCustomerFirstName"        ) var cCustomerFirstName        : String?         = null,
    @SerializedName("cCustomerMiddleName"       ) var cCustomerMiddleName       : String?         = null,
    @SerializedName("cCustomerLastName"         ) var cCustomerLastName         : String?         = null,
    @SerializedName("cCustomerEmailId"          ) var cCustomerEmailId          : String?         = null,
    @SerializedName("cPDFLink"                  ) var cPDFLink                  : String?         = null,
    @SerializedName("OrderStatusDetails"        ) var OrderStatusDetails        : String?         = null,
    @SerializedName("cTableName"        ) var cTableName        : String?         = null,
    @SerializedName("cSectionName"        ) var cSectionName        : String?         = null,
    @SerializedName("fCreditUsed"               ) var fCreditUsed               : Int?            = null,
    @SerializedName("nDeliveryType"             ) var nDeliveryType             : Int?            = null

    /* @SerializedName("nid"               ) var nid             : String?          = null,
     @SerializedName("order_ref"         ) var orderRef        : String?          = null,
     @SerializedName("customer_id"       ) var customerId      : String?          = null,
     @SerializedName("nbranch_id"        ) var nbranchId       : String?          = null,
     @SerializedName("ntable_id"         ) var ntableId        : String?          = null,
     @SerializedName("custom_module_id"  ) var customModuleId  : String?          = null,
     @SerializedName("nbrowser_id"       ) var nbrowserId      : String?          = null,
     @SerializedName("norder_status"     ) var norderStatus    : String?          = null,
     @SerializedName("payment_method"    ) var paymentMethod   : String?          = null,
     @SerializedName("order_type"        ) var orderType       : String?          = null,
     @SerializedName("pickup_time"       ) var pickupTime      : String?          = null,
     @SerializedName("pickup_date"       ) var pickupDate      : String?          = null,

     @SerializedName("corder_total"      ) var corderTotal     : String?          = null,
     @SerializedName("corder_note"       ) var corderNote      : String?          = null,
     @SerializedName("send_culary"       ) var sendCulary      : String?          = null,
     @SerializedName("accepted_on"       ) var acceptedOn      : String?          = null,
     @SerializedName("estimated_time"    ) var estimatedTime   : String?          = null,
     @SerializedName("rating"            ) var rating          : String?          = null,
     @SerializedName("has_rated"         ) var hasRated        : String?          = null,
     @SerializedName("ncreated_on"       ) var ncreatedOn      : String?          = null,
     @SerializedName("cutomer_name"      ) var cutomerName     : String?          = null,
     @SerializedName("table_name"        ) var tableName       : String?          = null,
     @SerializedName("created_date"      ) var createdDate     : String?          = null,
     @SerializedName("order_status_name" ) var orderStatusName : String?          = null,
     @SerializedName("section_name"       ) var section_name      : String?          = null,
     @SerializedName("order_type_name" ) var order_type_name : String?          = null,
     @SerializedName("tip" ) var tip : String?          = null,
     @SerializedName("items"             ) var items           : ArrayList<Items> = arrayListOf(),
     @SerializedName("cutomer"           ) var cutomer         : Cutomer?         = Cutomer()*/


):Parcelable
